// <auto-generated />
namespace CobaMVCNetFramework.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Section2Exercise3OverridingConvention : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Section2Exercise3OverridingConvention));
        
        string IMigrationMetadata.Id
        {
            get { return "202004151551095_Section2Exercise3OverridingConvention"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
